### PR TITLE
Fixed the coolblue checker and added MacICT/Amazon

### PR DESCRIPTION
**Pull request by galadril**

### CODE REVIEW

**Comment by galadril** [comment]
image

**Comment by galadril** [comment]
image

**Comment by galadril** [comment]
image

**Comment by galadril** [comment]
Still need to do the frontend for MacICT

**Comment by galadril** [comment]
Linked to the frontend PR
https://github.com/NiekNijland/rtx3000-notifier-frontend/pull/2

**Comment by galadril** [comment]
Heb toch MaxICT gedisabled.. vanwege comments op Tweakers > 
https://gathering.tweakers.net/forum/list_message/64947394#64947394

**Comment by galadril** [comment]
What do you think?
BTW is the backend still running? I havent received emails in ages 👍

**Comment by NiekNijland** [comment]
Nice work! yes the backend is still running but has only detected 2 stock changes in the past 2 days. And both of those were for the 3090 at Megekko.

**Comment by galadril** [comment]
Ah ok cool.. yeah im scouting for the 3080.. and not above 820 euro :D..
So its going to be hard

Op za 28 nov. 2020 om 20:04 schreef Niek Nijland <notifications@github.com>:

**Comment by galadril** [comment]
I didn't do the frontend for the new Amazon backend.. maybe you have time?

Op za 28 nov. 2020 om 20:06 schreef Mark Heinis <heinis.mark@gmail.com>:

**Pull request merged**
